### ISSUE TITLE
Configuration via env variables and Kubernetes

### ISSUE THREAD

**Issue by FaKod** [dadrus/heimdall#219]
Heimdall has the feature of being configured via env variables. These have to be prefixed with `HEIMDALL_`.
However, in K8s the names of service resources are populated as env variables in started Pods. So if a Service name is `heimdall` in the same namespace the env variables meets the prefix and the heimdall binary crashes with:

`goroutine 1 [running]:
github.com/dadrus/heimdall/internal/config/parser.merge({0xf04a40, 0xc00063d4d0?}, {0xf16960?, 0xc000721b90?})
	github.com/dadrus/heimdall/internal/config/parser/merge.go:17 +0x53d
github.com/dadrus/heimdall/internal/config/parser.koanfFromEnv.func2(0xc00079e398?, 0x0?)
	github.com/dadrus/heimdall/internal/config/parser/env.go:116 +0x109
github.com/knadh/koanf.(*Koanf).merge(0xc000673ad0, 0xc000673b00?, 0xc0000125a0)
	github.com/knadh/koanf@v1.4.2/koanf.go:395 +0xba
github.com/knadh/koanf.(*Koanf).Load(0x0?, {0x12501c0?, 0xc000673b00?}, {0x0?, 0x0?}, {0xc00079e590, 0x1, 0x0?})
	github.com/knadh/koanf@v1.4.2/koanf.go:118 +0x149
github.com/dadrus/heimdall/internal/config/parser.koanfFromEnv({0x109f2dd, 0x9})
	github.com/dadrus/heimdall/internal/config/parser/env.go:100 +0x208
github.com/dadrus/heimdall/internal/config/parser.(*configLoader).Load.func3()
	github.com/dadrus/heimdall/internal/config/parser/configloader.go:74 +0x25
github.com/dadrus/heimdall/internal/config/parser.(*configLoader).Load.func1(0xeea000?)
	github.com/dadrus/heimdall/internal/config/parser/configloader.go:48 +0x29
github.com/dadrus/heimdall/internal/config/parser.(*configLoader).Load(0xc0006c1ea0, {0xeea000?, 0xc0006e4900})
	github.com/dadrus/heimdall/internal/config/parser/configloader.go:73 +0x182
github.com/dadrus/heimdall/internal/config.NewConfiguration({_, _})
	github.com/dadrus/heimdall/internal/config/configuration.go:55 +0x592
reflect.Value.call({0xf40400?, 0x1110460?, 0x40d97f?}, {0x109bd57, 0x4}, {0xc000120b88, 0x1, 0x30?})
	reflect/value.go:584 +0x8c5
reflect.Value.Call({0xf40400?, 0x1110460?, 0x40dcc7?}, {0xc000120b88?, 0xfc2220?, 0xc000120b01?})
	reflect/value.go:368 +0xbc
go.uber.org/dig.defaultInvoker({0xf40400?, 0x1110460?, 0xc0005ab420?}, {0xc000120b88?, 0x1?, 0x125eb20?})
	go.uber.org/dig@v1.15.0/container.go:220 +0x28
go.uber.org/dig.(*constructorNode).Call(0xc00040a300, {0x125eb20, 0xc0006bf180})
	go.uber.org/dig@v1.15.0/constructor.go:154 +0x297
go.uber.org/dig.paramSingle.Build({{0x0, 0x0}, 0x0, {0x1262db0, 0x103ff60}}, {0x125eb20, 0xc0006bf180})
	go.uber.org/dig@v1.15.0/param.go:288 +0x2af
go.uber.org/dig.paramList.BuildList({{0x1262db0, 0xf3d040}, {0xc0006e1320, 0x3, 0x3}}, {0x125eb20, 0xc0006bf180})
	go.uber.org/dig@v1.15.0/param.go:151 +0xb9
go.uber.org/dig.(*Scope).Invoke(0xc0006bf180, {0xf3d040?, 0x1110748}, {0xc0000cb900?, 0x0?, 0xc0006d6340?})
	go.uber.org/dig@v1.15.0/invoke.go:85 +0x288
go.uber.org/fx.runInvoke({0x12538f0?, 0xc0006bf180?}, {{0xf3d040, 0x1110748}, {0xc0006b0f00, 0x7, 0x8}})
	go.uber.org/fx@v1.18.1/invoke.go:93 +0x1ff
go.uber.org/fx.(*module).executeInvoke(0xc0006bc120, {{0xf3d040, 0x1110748}, {0xc0006b0f00, 0x7, 0x8}})
	go.uber.org/fx@v1.18.1/module.go:174 +0x133
go.uber.org/fx.(*module).executeInvokes(0xc0006bc120)
	go.uber.org/fx@v1.18.1/module.go:155 +0xf1
go.uber.org/fx.New({0xc0000cbd50, 0x4, 0x0?})
	go.uber.org/fx@v1.18.1/app.go:530 +0x81e
github.com/dadrus/heimdall/cmd/serve.NewProxyCommand.func1(0xc0006c2a00?, {0x109c037?, 0x2?, 0x2?})
	github.com/dadrus/heimdall/cmd/serve/proxy.go:20 +0xfb
github.com/spf13/cobra.(*Command).execute(0xc0006c2a00, {0xc000413180, 0x2, 0x2})
	github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x1b1a2a0)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
github.com/dadrus/heimdall/cmd.Execute()
	github.com/dadrus/heimdall/cmd/root.go:24 +0x25
main.main()
	github.com/dadrus/heimdall/main.go:8 +0x17`

**Comment by dadrus** [comment]
I personally see two options here (not exclusive):
* Remove the vowels from the prefix to lower the probability of a name clash, or extend the prefix to contain something like `CFG`. So `HEIMDALL_` would either become `HMDL_` or `HEIMDALLCFG_`. Personally, I prefer the second one.
* Make the prefix configurable via an argument (e.g. named `--env-conf-prefix`) when starting heimdall.

I assume, this way name clashes can be avoided altogether. I personally don't see any other options to resolve such situations, as heimdall's configuration is typed and when configuration is loaded from env variables, the implementation verifies, that the expected type corresponds to the expected one (that's the reason for the panic).
