### ISSUE TITLE
Support HTTP 2 in proxy operation mode

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#412]
As of today heimdall supports only HTTP 1.x, which is fully ok for all services but proxy. Here support for for HTTP 2 would be very beneficial.

**Comment by lionello** [comment]
I have some services using gRPC and would benefit from having this.

**Comment by dadrus** [comment]
I see. Currently, I rather focus on making the available functionality more usable and resolve found bugs.
The HTTP 2 support means, I have to replace the HTTP engine for proxy. This is doable without affecting the decision service part, but requires some time, as depending on the engine, all the required middlewares, like for tracing, etc must be developed.

So I cannot promise to provide that support before Q3 this year.

**Comment by dadrus** [comment]
BTW. You're very welcome to join [Discord](https://discord.gg/qQgg8xKuyb) ;)

**Comment by lionello** [comment]
@dadrus sorry I didn't have time to test
