### ISSUE TITLE
Let heimdall discover JWKS and token introspection endpoints via oidc/oauth2 discovery documents

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#619]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I have discussed this feature request with the community.

### Describe the background of your feature request

As of today, the `oauth2_introspection`, respectively, the `jwt` authenticators require configuration of the introspection, respectively the JWKS endpoints. Since in many cases, these endpoints are also referenced in oidc/oauth2 discovery documents, it would be more convenient to let heimdall discover the above said endpoints via such document.

### Describe your idea

See above

### Are there any workarounds or alternatives?

Use the currenty available configuration

### Version

v0.7.0-alpha

**Comment by martin31821** [comment]
@dadrus I'd like to take this one over, if that's fine for you. Do you have already a design idea / document I could follow implementing?

**Comment by dadrus** [comment]
Sure. All contributions are very welcome.
Since you already joined the community in discord, describe your design idea for the FR in the ideas channel if it deviates from the description here and discuss it with the folks.

**Comment by dadrus** [comment]
My personal idea for that was/is to extend the `oauth2_introspection` and `jwt` authenticators with an additional property,  named e.g. `discovery_endpoint`, dealing with the corresponding functionality. On the authenticator level, either the existing endpoint or the new one mist be

**Comment by dadrus** [comment]
Sorry
 Hit the wrong button 😉
