### ISSUE TITLE
Allow rewrite of the original request url while forwarding the request to the upstream service

### ISSUE THREAD

**Issue by dadrus** [dadrus/heimdall#683]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/dadrus/heimdall/blob/main/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/dadrus/heimdall/blob/main/CONTRIBUTING.md)."
- [X] I have discussed this feature request with the community.

### Describe the background of your feature request

As of today, when operating in proxy mode, heimdall does not support any types of path rewrites while forwarding the requests to the upstream service. This is however too limiting as the external (publicly visible) API does not need to correspond (and in many cases it is not) to the internal API implemented by a service.

So having an external API, like `https://foo.bar/api/v1/something` and an internal one `https://internal.host/something` is not possible, as heimdall always uses the path from the original request (here `api/v1/something`).

### Describe your idea

Allow path rewrites of the original request before forwarding the request to the upstream. The most important as of today seem to be:
* stripping a path prefix, e.g. if the path of the original request looks like `/api/v1/something` it should be possible to remove `/api/v1`.
* adding a path prefix, e.g. if the path of the original request looks like `/` and the corresponding upstream service exposes it on `/somename`, it should be possible to forward the request to that upstream service using `/somename` path
* stripping query parameters - this is useful if some query parameters contains data, heimdall operates on and are not related to the functionality of the upstream service; e.g. if an api key is present as query parameter.

Following approaches have been discussed with the community:

#### Alternative 1
The upstream property would be extended from a simple string to something like

```.yaml
upstream:
  url: https://my-backend
  path_rewrite:
     strip_prefix: /foo
```

The `path_rewrite` property would allow usage of different path rewrite options, like e.g. `add_prefix`, or something else. 

**Pros:**

* Everything is just yaml
* Is open for extensibility in the future. E.g. if any other type of routing middleware is required, it easy to introduce another property for that.
* No breaking changes, as it is possible to parse the content either as string (as it is today), or as an object
* Very fast in sense of the execution time - fraction of ns.

**Cons:**
* It is not obvious which path is stripped, respectively modified
* Kind of verbose

**Opens:**

* it is unclear what to do if multiple middleware (path rewrite options) are used, which work on the same part of the url

#### Alternative 2
As with the previous alternative, this one would extend, respectively change the upstream property. To support comprehensibility, the `upstream` property would be renamed to `forward_to`. In the simplest case, it would be just the host and the port of the upstream service:

```.yaml
forward_to: my-backend:8080
```

If usage of middlewares is required to rewrite some parts of the urls, it would be an object, like:

```.yaml
forward_to:
  host: my-backend:8080
  rewrite:
     scheme: http
     strip_path_prefix: /foo
     strip_query_parameters: [ api_key ]
```

The `rewrite` property would allow usage of different rewrite options, like e.g. `add_path_prefix` to add a prefix, `scheme` to change the HTTP scheme, or something else. 

**Pros:**

* Everything is just yaml
* Is open for extensibility in the future. E.g. if any other type of middleware is required, it easy to introduce another property for that.
* Very fast in sense of the execution time - fraction of ns.
* Compared to alternative 1, it is clear what is rewritten, changed compared to the original request

**Cons:**
* Kind of verbose

**Opens:**

* it is unclear what to do if multiple middleware (path rewrite options) are used, which work on the same part of the url

#### Alternative 3

This alternative would allow usage of templates in the upstream property. So if some type of path rewrite is required, one could do something like this:

```.yaml
upstream: {{ https://my-backend | StripPrefix "/foo" }}
```

or any other type of path rewrite middleware which may come in the future. E.g. Usage of a middleware to add a prefix, would look like this:

 ```.yaml
upstream: {{ https://my-backend | AddPrefix "/foo" }}
```

**Pros:**

* No breaking changes. One can either use the upstream url as already possible, or as shown in the examples
* Very simple in sense of usage
* Open for simple extensions.
* Multiple middleware functions can just be piped

**Cons:**

* It is not obvious which path is stripped, respectively modified
* It would be possible to combine multiple middleware functions, which should not be used together. E.g upstream: `{{ https://my-backend | StripPrefix "/foo" | AddPrefix "/foo" }}` (at least it looks strange for me right now)
* If there is a need for a more complex middleware in the future, it might be challenging to implement without breaking changes for the rule configuration
* Will require a around 1.5 µs for rendering.

#### Alternative 4

The one would be based on templates as well, but in the ngnix like style:

```.yaml
upstream: {{ .Scheme }}://my-backend{{ .PathURI | StripPrefix "/foo" }}
```

So, the path, query, etc must be explicitly defined.

**Pros:**

* Open for simple extensions.
* Multiple middleware functions can just be piped
* Makes it clear, what are the parts of the upstream url and where do they come from.

**Cons:**

* Introduces a breaking change
* Pretty complex
* It would be possible to combine multiple middleware functions, which should not be used together. E.g upstream: `https://my-backend{{ .PathURI | StripPrefix "/foo" | AddPrefix "/foo" }}` (at least it looks strange for me right now)
* If there is a need for a more complex middleware in the future, it might be challenging to implement without breaking changes for the rule configuration
* If there is a need for other types of middleware for upstream request routing in the future, it might be challenging to implement without breaking changes for the rule configuration
* Will require around 1.5µs for rendering

#### Alternative 5

This alternative is based on template usage and has two possible flavors. The idea is as follows:

```.yaml
upstream: {{ .Request.URL | SetScheme "http" | SetHost "srv-1" | StripPathPrefix "/foo" }}
```

So, here access to the original request, which was matched based on its url, is granted in the template (reduced to the URL usage only) and then transformed by a pipeline of different middleware functions. The `SetHost` middleware would be mandatory to set the upstream hostname.

In principle `.Request.URL` can also be considered as syntactic sugar. So the definition could also be simplified to

```.yaml
upstream: {{ SetScheme "http" | SetHost "srv-1" | StripPathPrefix "/foo" }}
```

This second flavor would potentially reduce error potential as there would be only one way (without ambiguities) to define the upstream url (via a middleware pipeline).

**Pros:**

* very simple in sense of usage
* open for simple extensions, which would work on the actual URL only
* multiple middleware functions can just be piped
* it is very explicit

**Cons:**
* introduces a breaking change
* it would be possible to combine multiple middleware functions, which should not be used together. E.g `upstream: {{ .Request.URL | SetHost "srv-1" | StripPrefix "/foo" | AddPrefix "/foo" }}` (at least it looks strange for me right now)
* if there is a need for a more complex middleware in the future, it might be challenging to implement without breaking changes for the rule configuration
* will require around 1-2µs for rendering. This is the slowest one from all considered alternatives.

### Are there any workarounds or alternatives?

No

### Version

v0.8.1-alpha

### Additional Context

Alternatives 2 and 5 seems to be the most interesting ones

_No response_

**Comment by raphaeltm** [comment]
I'm a fan of alternative 2. Down the line I think there's also value in having the yaml structure because we can easily add autocompletion using json schema. I think that would be helpful for DX.
